name: Create repository webhook for homelab-infra

run-name: create-repository-webhook-homelab-infra

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  create-repository-webhook:
    uses: ./.github/workflows/create_repository_webhook.yml
    with:
      repository_name: 'homelab-infra'
      repository_owner: 'KarafrOrg'
      gh_admin_token: '${{ secrets.GH_ADMIN_TOKEN }}'
      # language=bash
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_HOSTS: ${{ secrets.SERVER_HOSTS }}
      SSH_USER: ${{ secrets.SSH_USER }}
